cookbook/urls.py
from django.urls import path, include
from . import views


app_name = 'cookbook'

urlpatterns = [
    path('', views.RecipeListView.as_view(),  name='recipe_list'),
    path('user_cookbook/', views.user_cookbook, name='user_cookbook'),
    path('<int:year>/<int:month>/<int:day>/<slug:recipe>/',
         views.recipe_detail, name='recipe_detail'),
    path('search/', views.recipe_search_view, name='recipe_search'),
    path('add/', views.AddRecipe.as_view(), name='add_recipe'),
    path('<int:recipe_id>/editing/',
         views.EditRecipe.as_view(), name='edit_recipe'),
    path('<int:recipe_id>/deletion/', views.delete_recipe, name='delete_recipe'),
    path('assessment/', include('likes.urls', namespace='likes'))
]

course_work_testing/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='account')),
    path('cookbook/', include('cookbook.urls', namespace='cookbook')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

likes/urls.py
from django.urls import path
from . import views


app_name = 'likes'

urlpatterns = [
    path('<int:recipe_id>/like/', views.like_the_recipe, name='like_recipe'),
    path('<int:recipe_id>/dislike/', views.dislike_the_recipe, name='dislike_recipe'),
]

cookbook/models.py
from django.contrib.contenttypes.fields import GenericRelation
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse

from likes.models import Like


class RecipePost(models.Model):
    title = models.CharField(max_length=50, unique=True)
    slug = models.CharField(max_length=50,
                            unique_for_date='publish',
                            blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE,
                               related_name='recipe_posts')  # Many to one
    body = models.TextField(unique=True)
    publish = models.DateTimeField(default=timezone.now)
    photo = models.ImageField(blank=True)
    updated = models.DateTimeField(auto_now=True)
    likes = GenericRelation(Like)

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('cookbook:recipe_detail',
                       args=[self.publish.year,
                             self.publish.month,
                             self.publish.day,
                             self.slug])

    @property
    def total_likes(self):
        return self.likes.count()

cookbook/forms.py
from django import forms
from .models import RecipePost


class SearchForm(forms.Form):
    query = forms.CharField()


class AddRecipeForm(forms.ModelForm):
    class Meta:
        model = RecipePost
        fields = ['title', 'body', 'photo']
        exclude = ['author']


class EditRecipeForm(forms.ModelForm):
    class Meta:
        model = RecipePost
        fields = ['title', 'body']

cookbook/views.py
from django.shortcuts import render, get_object_or_404, redirect

from .models import RecipePost
from django.views.generic import ListView
from .forms import SearchForm, AddRecipeForm, EditRecipeForm
from django.views.generic import View

from django.contrib.auth.decorators import login_required

from django.contrib import messages
from likes import services as likes_services
from . import services


class RecipeListView(ListView):
    queryset = RecipePost.objects.all()
    context_object_name = 'recipes'
    paginate_by = 3
    template_name = 'cookbook/cookbook_list.html'


# tested
def recipe_detail(request, year, month, day, recipe):
    recipe = services.get_recipe_with_date(year, month, day, recipe)
    print(recipe.pk)
    is_fan = likes_services.is_fan(recipe, request.user)
    print(is_fan)
    likes = recipe.total_likes
    print(f'{likes}')
    return render(request, 'cookbook/recipe_detail.html',
                  {'recipe': recipe, 'is_fan': is_fan,
                   'total_likes': likes})


# tested (create TDD!!!)
def recipe_search_view(request):
    form = SearchForm()
    results = []
    query = None
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            results = services.get_recipe_with_title(query)
            print(results)
    return render(request, 'cookbook/search.html',
                  {'form': form, 'query': query,
                   'results': results, 'section': 'search'})


# tested
class AddRecipe(View):
    form_class = AddRecipeForm
    template_name = ['cookbook/adding_recipe/add_recipe.html',
                     'cookbook/adding_recipe/successfully_added.html']

    def get(self, request):
        if not request.user.is_authenticated:
            return redirect('account:login')
        form = self.form_class()
        return render(request, self.template_name[0],
                      {'form': form, 'section': 'user_add_recipe'})

    def post(self, request):
        if not request.user.is_authenticated:
            return redirect('account:login')

        form = self.form_class(request.POST, request.FILES)
        template = self.template_name[0]
        context = {'form': form, 'section': 'user_add_recipe'}
        if form.is_valid():
            services.add_recipe(request.user.id, form, form.cleaned_data)
            template = self.template_name[1]
            context = {}
        print(form.errors)

        return render(request, template, context)


@login_required
def user_cookbook(request):
    user_recipes = services.get_user_recipes(request.user)
    return render(request,
                  'cookbook/user_cookbook.html',
                  {'section': 'user_cookbook',
                   'user_recipes': user_recipes})


class EditRecipe(View):
    form_class = EditRecipeForm
    template_name = ['cookbook/editing_recipe/edit.html',
                     'cookbook/editing_recipe/done_editing.html']

    def get(self, request, recipe_id):
        recipe = services.get_recipe_with_id(recipe_id)
        form = self.form_class(initial={'title': recipe.title,
                                        'body': recipe.body})
        return render(request, self.template_name[0],
                      {'form': form})

    def post(self, request, recipe_id):
        if not request.user.is_authenticated:
            return redirect('account:login')
        recipe = services.get_recipe(request.user, recipe_id)
        form = self.form_class(request.POST, instance=recipe)
        template = self.template_name[0]
        context = {'form': form}
        if form.is_valid():
            services.save_recipe(recipe)
            template = self.template_name[1]
            context = {}
        return render(request, template, context)


# tested
def delete_recipe(request, recipe_id):
    template = 'cookbook/fail_deleting.html'
    if not request.user.is_authenticated:
        return redirect('account:login')
    recipe = services.get_recipe(request.user, recipe_id)
    if recipe:
        services.delete_recipe(recipe.id)
        template = 'cookbook/success_deleted.html'
    return render(request, template)


def find_recipe_with_id_and_user(recipe_id, author):
    return RecipePost.objects.all().filter(pk=recipe_id,
                                           author=author)

cookbook/templates/cookbook/cookbook_list.html
{% extends 'base.html' %}

{% block title %}CookBook{% endblock %}

{% block content %}
    <h1>Welcome to cookbook!</h1>
    {% for recipe in recipes %}
        <a href="{{ recipe.get_absolute_url }}">{{ recipe.title }}</a>
        <p class="date">
            Published {{ recipe.publish }} by {{ recipe.author }}
        </p>
        {% if recipe.photo.url is not None %}
            <img src='{{ recipe.photo.url }}' class="photo">
        {% endif %}
        {{ recipe.body|truncatewords:30|linebreaks }}
    {% endfor %}

    {% include 'pagination.html' with page=page_obj %}
{% endblock %}

cookbook/templates/cookbook/fail_deleting.html
{% extends 'base.html' %}

{% block title %}Delete Fail{% endblock %}

{% block content %}
    <h1>Your recipe has not been deleted.</h1>
{% endblock %}

cookbook/templates/cookbook/recipe_detail.html
{% extends 'base.html' %}

{% block title %}{{ recipe.title }}{% endblock %}

{% block content %}
    <h1>{{ recipe.title }}</h1>
    <p class="date">
        Published {{ recipe.publish }} by {{ recipe.author }}
    </p>
    {% if recipe.photo.url is not None %}
        <img src="{{ recipe.photo.url }}" alt="">
    {% endif %}

    {{ recipe.body|linebreaks }}

    {% if is_fan %}
        <a href="{% url 'cookbook:likes:dislike_recipe' recipe.id%}" class="dislike-button">Dislike</a>
    {% else %}
        <a href="{% url 'cookbook:likes:like_recipe' recipe.id%}" class="like-button">Like</a>
    {% endif %}
    <h3>Total likes: {{ total_likes }}</h3>

    {% if recipe.author == request.user %}
        <table>
        <tr>
            <td><a href="{% url 'cookbook:edit_recipe' recipe.id %}">Edit recipe</a></td>
            <td><p>/</p></td>
            <td><a href="{% url 'cookbook:delete_recipe' recipe.id %}">Delete</a></td>
        </tr>
        </table>
    {% endif %}
{% endblock %}

cookbook/templates/cookbook/search.html
{% extends 'base.html' %}

{% block title %}Search{% endblock %}

{% block content %}
    {% if query %}
        {% if results %}
            <h1>Posts containing "{{ query }}"</h1>
            <h3>
                {% with results.count as totat_resuts %}
                    Found {{ totat_resuts }} result{{ totat_resuts|pluralize }}
                {% endwith %}
            </h3>
            {% for post in results %}
                {% if post.photo.url is not None %}
                    <img src="{{ post.photo.url }}" alt="">
                {% endif %}
                <h4><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h4>
                {{ post.body|truncatewords:5 }}
            {% endfor %}
        {% else %}
            <p>There are no results for your query.</p>
        {% endif %}
    {% else %}
        <h1>Search for posts</h1>
        <form action="." method="get">
            {{ form.as_p }}
            <input type="submit" value="Search">
        </form>
    {% endif %}
{% endblock %}

cookbook/templates/cookbook/success_deleted.html
{% extends 'base.html' %}

{% block title %}Successfully deleted{% endblock %}

{% block content %}
    <h1>Your recipe has been successfully deleted.</h1>
{% endblock %}

cookbook/templates/cookbook/user_cookbook.html
{% extends 'base.html' %}

{% block title %}Your cookbook{% endblock %}

{% block content %}
    <h1>Cookbook</h1>
    <p>Welcome to your cookbook!</p>
    {% for recipe in user_recipes %}
        <a href="{{ recipe.get_absolute_url }}">{{ recipe.title }}</a>
        <p class="date">
            Published {{ recipe.publish }}
        </p>
        {% if recipe.photo.url is not None %}
            <img src='{{ recipe.photo.url }}' class="photo">
        {% endif %}

        {{ recipe.body|truncatewords:30|linebreaks }}
    {% endfor %}
{% endblock %}